# Site settings
title: Zane's Blog
description: "Language Learning | Life | Thoughts"  # used in site head

# register on google analytics and replace this token
google_analytics: 
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
disqus_url: https-zasman-github-io.disqus.com
disqus_id: https-zasman-github-io.disqus.com
# footer details. Deleting the value would remove it from footer.
github_username:  zasman
stackoverflow_username: 5331859/jason-bourne
copyright_name: Zane
rss : true

# used for portfolio on home page
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
